WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 1040
FPS = 60

GRID_COLS = 20
GRID_ROWS = 20
TILE_SIZE = 46
GRID_PADDING = 8
HEADER_HEIGHT = 90
EXCAVATION_TOP_BAR_HEIGHT = 48
EXCAVATION_TOP_BAR_WIDTH = 420
EXCAVATION_TOP_BAR_TOP = 24
GRID_TOP = EXCAVATION_TOP_BAR_TOP + EXCAVATION_TOP_BAR_HEIGHT + 20
GRID_LEFT = (WINDOW_WIDTH - (GRID_COLS * TILE_SIZE)) // 2
GRID_RIGHT_MARGIN = GRID_LEFT

ACTION_BAR_HEIGHT = 70
ACTION_BAR_GAP = 12
NARRATION_BOX_HEIGHT = 70

BACKGROUND_COLOR = (24, 24, 28)
PANEL_COLOR = (38, 38, 46)
GRID_LINE_COLOR = (70, 70, 85)
TEXT_COLOR = (235, 235, 240)
HOVER_COLOR = (90, 90, 110)

# Cavern Archeology UI Theme Colors
THEME_BG = (28, 25, 23)             # Deep warm-earth panel interior
THEME_TEXT_GOLD = (245, 215, 120)    # Bright archaeological gold
THEME_TEXT_CREAM = (235, 225, 210)   # Creamy parchment white
THEME_TEXT_SHADOW = (20, 12, 8)      # Offset drop shadow for text
THEME_WOOD_DARK = (48, 28, 16)       # Walnut shadow / dark bevel
THEME_WOOD_MED = (96, 56, 36)        # Oak base wood
THEME_WOOD_LIGHT = (168, 110, 72)    # Light oak edge highlight
THEME_STONE_DARK = (28, 28, 34)      # Slate shadow
THEME_STONE_MED = (48, 48, 56)       # Deep slate base
THEME_STONE_LIGHT = (85, 85, 100)    # Slate edge highlight
THEME_GOLD_ACCENT = (235, 195, 80)   # Glowing gold accent (active/hover)
THEME_GOLD_SHADOW = (150, 115, 35)   # Antique brass/gold shadow


TITLE_TEXT = "Fossil Rush Rivals"
PHASE_TITLE = "Title Screen"
PHASE_JOURNAL = "Field Journal"
PHASE_EXCAVATION = "Excavation Phase"
PHASE_DIG_COMPLETE = "Dig Site Closed"
PHASE_LAB = "Laboratory Verification"
PHASE_MARKET = "Midnight Market"
NARRATION_TEXT = "Hover a tile to inspect it."

BUTTON_WIDTH = 220
BUTTON_HEIGHT = 48
BUTTON_GAP = 16

JOURNAL_CARDS_PER_PAGE = 10

MATCH_SEED = 12345
EXCAVATION_DURATION_MS = 60_000
COUNTDOWN_STEP_MS = 300
COUNTDOWN_FADE_IN_MS = 80
COUNTDOWN_FADE_OUT_MS = 80
POPUP_FADE_IN_MS = 250
POPUP_HOLD_MS = 500
POPUP_FADE_OUT_MS = 250

MOVE_COOLDOWN_MS = 160
AI_MOVE_BUFFER_MS = 80
ACTION_COOLDOWNS_MS = {
	"careful_dig": 500,
	"rush_dig": 450,
	"survey": 600,
	"claim_zone": 300,
}

ACTION_POSE_MS = 220

SURVEY_COOLDOWN_MS = 500
CLAIM_DURATION_MS = 4000

AI_THINK_INTERVAL_RANGE_MS = (250, 500)

RUSH_ACTION_LIMIT = 5
CLAIM_ACTION_LIMIT = 5

CAREFUL_DAMAGE_CHANCE = 0.2
RUSH_DAMAGE_CHANCE = 0.5

AI_DEBUG_LOG = True

ACTIVE_TILE_COUNT = 260

OBSTACLE_TILE_MIN = 14
OBSTACLE_TILE_MAX = 24
OBSTACLE_CLUSTER_MIN = 3
OBSTACLE_CLUSTER_MAX = 6
OBSTACLE_CLUSTER_SIZE_MIN = 5
OBSTACLE_CLUSTER_SIZE_MAX = 10
OBSTACLE_CLUSTER_SPACING = 2

PLAYER_LABEL = "Player"
AI_LABEL = "Rival AI"

ACTION_SURVEY = "survey"
ACTION_CAREFUL = "careful_dig"
ACTION_RUSH = "rush_dig"
ACTION_CLAIM = "claim_zone"

ACTION_LABELS = {
	ACTION_SURVEY: "Survey",
	ACTION_CAREFUL: "Careful Dig",
	ACTION_RUSH: "Rush Dig",
	ACTION_CLAIM: "Claim Zone",
}

DIRECTION_KEYS = ["n", "ne", "e", "se", "s", "sw", "w", "nw"]
ANIMATION_FRAMES = {
	"idle": ["idle_0", "idle_1"],
	"walk": ["walk_0", "walk_1", "walk_2"],
}
ANIMATION_FRAME_MS = {
	"idle": 500,
	"walk": 120,
}

LAB_AUTHENTICATE = "Authenticate"
LAB_RESTORE = "Restore"
LAB_SHOWCASE = "Showcase Prep"

LAB_CHOICES = [LAB_AUTHENTICATE, LAB_RESTORE, LAB_SHOWCASE]

LAB_AUTHENTICATE_SUCCESS = 0.8
LAB_RESTORE_SUCCESS = 0.75

LAB_SUB_CHOOSE_FOCUS = "choose_focus"
LAB_SUB_CONFIRM = "confirm"
LAB_SUB_RESULT = "result"

MARKET_SUB_INTRO = "intro"
MARKET_SUB_REVEAL = "reveal"
MARKET_SUB_FINAL = "final"
