WINDOW_WIDTH = 960
WINDOW_HEIGHT = 980
FPS = 60

GRID_COLS = 20
GRID_ROWS = 20
TILE_SIZE = 32
GRID_PADDING = 8
HEADER_HEIGHT = 90
GRID_TOP = HEADER_HEIGHT + 20
GRID_LEFT = (WINDOW_WIDTH - (GRID_COLS * TILE_SIZE)) // 2
GRID_RIGHT_MARGIN = GRID_LEFT

ACTION_BAR_HEIGHT = 70
ACTION_BAR_GAP = 12
NARRATION_BOX_HEIGHT = 70

BACKGROUND_COLOR = (24, 24, 28)
PANEL_COLOR = (38, 38, 46)
GRID_LINE_COLOR = (70, 70, 85)
TEXT_COLOR = (235, 235, 240)
HOVER_COLOR = (90, 90, 110)

TITLE_TEXT = "Fossil Rush Rivals"
PHASE_TITLE = "Title Screen"
PHASE_JOURNAL = "Field Journal"
PHASE_EXCAVATION = "Excavation Phase"
PHASE_LAB = "Laboratory Verification"
PHASE_MARKET = "Midnight Market"
NARRATION_TEXT = "Hover a tile to inspect it."

BUTTON_WIDTH = 220
BUTTON_HEIGHT = 48
BUTTON_GAP = 16

MATCH_SEED = 12345
PLAYER_ACTIONS = 15
AI_ACTIONS = 15

RUSH_ACTION_LIMIT = 3
CLAIM_ACTION_LIMIT = 3

AI_DEBUG_LOG = True

ACTIVE_TILE_COUNT = 260

PLAYER_LABEL = "Player"
AI_LABEL = "Rival AI"

ACTION_SURVEY = "survey"
ACTION_CAREFUL = "careful_dig"
ACTION_RUSH = "rush_dig"
ACTION_CLAIM = "claim_zone"

ACTION_LABELS = {
	ACTION_SURVEY: "Survey",
	ACTION_CAREFUL: "Careful Dig",
	ACTION_RUSH: "Rush Dig",
	ACTION_CLAIM: "Claim Zone",
}

LAB_AUTHENTICATE = "Authenticate"
LAB_RESTORE = "Restore"
LAB_SHOWCASE = "Showcase Prep"

LAB_CHOICES = [LAB_AUTHENTICATE, LAB_RESTORE, LAB_SHOWCASE]

LAB_AUTHENTICATE_SUCCESS = 0.8
LAB_RESTORE_SUCCESS = 0.75

LAB_SUB_CHOOSE_FOCUS = "choose_focus"
LAB_SUB_CONFIRM = "confirm"
LAB_SUB_RESULT = "result"

MARKET_SUB_INTRO = "intro"
MARKET_SUB_REVEAL = "reveal"
MARKET_SUB_FINAL = "final"
